// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	schemas "github.com/foolish15/shorten-url-service/internal/schemas"
	mock "github.com/stretchr/testify/mock"
)

// I is an autogenerated mock type for the I type
type I struct {
	mock.Mock
}

// IsBlock provides a mock function with given fields: u, lblock
func (_m *I) IsBlock(u string, lblock []schemas.Block) bool {
	ret := _m.Called(u, lblock)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, []schemas.Block) bool); ok {
		r0 = rf(u, lblock)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
