// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// RouteInterface is an autogenerated mock type for the RouteInterface type
type RouteInterface struct {
	mock.Mock
}

// Route provides a mock function with given fields: e
func (_m *RouteInterface) Route(e *echo.Echo) {
	_m.Called(e)
}
