// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	link "github.com/foolish15/shorten-url-service/internal/repositories/link"
	mock "github.com/stretchr/testify/mock"

	repositories "github.com/foolish15/shorten-url-service/internal/repositories"

	schemas "github.com/foolish15/shorten-url-service/internal/schemas"

	sql "database/sql"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Count provides a mock function with given fields: queries
func (_m *Repository) Count(queries ...repositories.Query) (int64, error) {
	_va := make([]interface{}, len(queries))
	for _i := range queries {
		_va[_i] = queries[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 int64
	if rf, ok := ret.Get(0).(func(...repositories.Query) int64); ok {
		r0 = rf(queries...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...repositories.Query) error); ok {
		r1 = rf(queries...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: lnk
func (_m *Repository) Create(lnk *schemas.Link) error {
	ret := _m.Called(lnk)

	var r0 error
	if rf, ok := ret.Get(0).(func(*schemas.Link) error); ok {
		r0 = rf(lnk)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ID
func (_m *Repository) Delete(ID uint) error {
	ret := _m.Called(ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: queries
func (_m *Repository) Find(queries ...repositories.Query) ([]schemas.Link, error) {
	_va := make([]interface{}, len(queries))
	for _i := range queries {
		_va[_i] = queries[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []schemas.Link
	if rf, ok := ret.Get(0).(func(...repositories.Query) []schemas.Link); ok {
		r0 = rf(queries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schemas.Link)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...repositories.Query) error); ok {
		r1 = rf(queries...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// First provides a mock function with given fields: queries
func (_m *Repository) First(queries ...repositories.Query) (schemas.Link, error) {
	_va := make([]interface{}, len(queries))
	for _i := range queries {
		_va[_i] = queries[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 schemas.Link
	if rf, ok := ret.Get(0).(func(...repositories.Query) schemas.Link); ok {
		r0 = rf(queries...)
	} else {
		r0 = ret.Get(0).(schemas.Link)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...repositories.Query) error); ok {
		r1 = rf(queries...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// New provides a mock function with given fields: idb
func (_m *Repository) New(idb ...interface{}) (link.Repository, error) {
	var _ca []interface{}
	_ca = append(_ca, idb...)
	ret := _m.Called(_ca...)

	var r0 link.Repository
	if rf, ok := ret.Get(0).(func(...interface{}) link.Repository); ok {
		r0 = rf(idb...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(link.Repository)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(idb...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetDB provides a mock function with given fields: idb
func (_m *Repository) SetDB(idb interface{}) error {
	ret := _m.Called(idb)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(idb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartTransaction provides a mock function with given fields:
func (_m *Repository) StartTransaction() (*sql.Tx, link.Repository, error) {
	ret := _m.Called()

	var r0 *sql.Tx
	if rf, ok := ret.Get(0).(func() *sql.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	var r1 link.Repository
	if rf, ok := ret.Get(1).(func() link.Repository); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(link.Repository)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TranslateOrderField provides a mock function with given fields: input
func (_m *Repository) TranslateOrderField(input string) string {
	ret := _m.Called(input)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Update provides a mock function with given fields: lnk
func (_m *Repository) Update(lnk *schemas.Link) error {
	ret := _m.Called(lnk)

	var r0 error
	if rf, ok := ret.Get(0).(func(*schemas.Link) error); ok {
		r0 = rf(lnk)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
