// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OrderInterface is an autogenerated mock type for the OrderInterface type
type OrderInterface struct {
	mock.Mock
}

// TranslateOrderField provides a mock function with given fields: input
func (_m *OrderInterface) TranslateOrderField(input string) string {
	ret := _m.Called(input)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
