// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SetDBInterface is an autogenerated mock type for the SetDBInterface type
type SetDBInterface struct {
	mock.Mock
}

// SetDB provides a mock function with given fields: idb
func (_m *SetDBInterface) SetDB(idb interface{}) error {
	ret := _m.Called(idb)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(idb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
